kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: "{{ .Values.name }}"
  labels:
    app: "{{ .Values.name }}"
spec:
  to:
    kind: Service
    name: "{{ .Values.name }}"
    weight: 100
  port:
    targetPort: http
  wildcardPolicy: None
